#!/bin/sh
# MIT License

# Copyright (c) 2022 Pascal Martin.
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# A script to record and view on the screen the image from the boroscope.
#
# Usage: boroscope <file>
#
# This small script makes it easier to start viewing from the Boroscope
# without having to remember, retrieve, or even retype, all the details.
#
echo "Keyboard/Mouse controls:
q   Exit  | ->  Forward | f            Full screen
p   Pause | <-  Back    | Left click   Full screen
m   Mute  | s   Step    | Richt click  Jump
"
/usr/local/bin/bsf -i tcp:192.168.10.123:7060 | /usr/bin/tee $* | /usr/bin/ffplay -hide_banner -f mjpeg -

